### PR TITLE
Update: add RSE story Adam Sparks

### PR DESCRIPTION
**Pull request by likeajumprope**

### CODE REVIEW

**Comment by manodeep** [comment]
@likeajumprope I will leave a review later on but noticed that the title at the top of the post is from the previous RSE story.

**Comment by likeajumprope** [comment]
Ohh good catch! Will change that.

**Review by manodeep — COMMENTED** [review]
Other than the title, everything else looks fine. 

The only thing that stood out was the sentence starting with "_The mobile implementation .... " - is that a markdown footnote or something?

**Comment by likeajumprope** [comment]
I have updated the title. The underscore in front of some paragraphs ("_The mobile implementation .... ") renders to italics for me when I do preview...

**Pull request merged**
