### PR TITLE
About: Delete old membership graph

### PR DESCRIPTION
**Pull request by orchid00**
Delete old membership graph @manodeep

### CODE REVIEW

**Comment by manodeep** [comment]
Is there another graph that we could add?

**Comment by orchid00** [comment]
not now, I just got access to the members list

**Comment by manodeep** [comment]
Huh - somehow didn't get the notification about the updated plot! Weird.

This looks great!

**Comment by manodeep** [comment]
I see that you closed the PR - are you planning to open a new PR and simply update the plot?

Also, should we add the plotting script somewhere (say, gist.github) so that future SC members can easily remake the plot from the membership data?

**Pull request closed without merging**
