### PR TITLE
Added post for 2018 survey slides.

### PR DESCRIPTION
**Pull request by nrmay**

### CODE REVIEW

**Comment by manodeep** [comment]
@rowlandm Could you check what the file renders as? I was trying to but have not yet managed to get `gem` on my OSX laptop. Might require some updating on the install instructions...

**Comment by manodeep** [comment]
Looks like there are two posts with the survey results. Simply deleting one of the files might be sufficient

**Comment by rowlandm** [comment]
good point.

this link errors out
https://rse-aunz.github.io/survey/2018/2019/08/assets/RSE_Survey_2018_AU_v3.pdf

Regards,

Rowland
_______________

Rowland Mosbergen
Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

E:  rowland.mosbergen@unimelb.edu.au

M: +61 3 834 46623


I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by manodeep** [comment]
And the final link to the survey slides pdf is resulting in a `404`. Let me see if I can fix the errors.

**Pull request merged**
